server:
  port: 8088
security:
  oauth2:
    client:
      clientId: admin
      clientSecret: 1234
spring:
  application:
    name: 'server-auth'
  datasource:
    password: 'omjbr1lcr727wzv5'
    username: 'ix47y9wr4463uh7x'
    url: jdbc:mysql://dcrhg4kh56j13bnu.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/becuuzhi3samphf0?serverTimezone=GMT
    driver-class-name: org.mariadb.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update


eureka:
  client:
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://eureka-server-boa-entrega.herokuapp.com/eureka

token:
  access:
    expire: 60000