server:
  port: 8088
security:
  oauth2:
    client:
      clientId: admin
      clientSecret: 1234
spring:
  application:
    name: 'server-auth'
 

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://eureka-server-boa-entrega.herokuapp.com/eureka

token:
  access:
    expire: 60000