server:
  port: 8088
security:
  oauth2:
    client:
      clientId: admin
      clientSecret: 1234
spring:
  application:
    name: 'server-auth'
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/authDB
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update


token:
  access:
    expire: 60000
